directories:
  output: release/${version}
  buildResources: build
appId: YourAppID
asar: true
files:
  - filter:
      - dist-electron
      - dist
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}_${version}.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
electronVersion: 23.1.1
